### ISSUE TITLE
Safari support

### ISSUE THREAD

**Issue by kkaefer** [mapbox/top-issues#5]
I'm unable to get this running in Safari. The error message I get is:

![](https://cloud.githubusercontent.com/assets/52399/23776859/afc1f94e-04e5-11e7-8dc2-9c0a1992bae3.png)

I'm not seeing any requests to the Github API being made.

**Comment by lucaswoj** [comment]
Ah. It would appear that Safari doesn't support [`fetch`](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API). I suppose there's no harm in adding a [polyfill](https://github.com/github/fetch).
